{{- if .Values.prometheus.prometheusK8s.ruleSelector }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus.name" . }}-k8s-rules
  namespace: {{ .Release.Namespace }}
  labels:
    role: prometheus-rulefiles
    prometheus: {{ .Values.prometheus.prometheusK8s.prometheusLabel }}
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
data:
{{ toYaml .Values.prometheus.configmap.data | indent 2}}
{{- end }}