apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: {{ .Values.prometheus.prometheusK8s.prometheusLabel }}
    expose: "{{ .Values.prometheus.service.expose }}"
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: prometheus-{{ .Values.prometheus.prometheusK8s.prometheusName }}
{{- if .Values.prometheus.service.annotations }}
  annotations:
{{ toYaml .Values.prometheus.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: {{ .Values.prometheus.prometheusK8s.prometheusName }}
    app: prometheus
